version: "2.2"
# ipv6 is not supported in version 3

services:
  db:
    image: mysql:8.1.0
    # mem_limit: 512m
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: chatapp

  chatapp-deps:
    image: faust.cs.fau.de:5000/chatapp-deps
    build:
      context: ./server
      dockerfile: Dockerfile.deps
    scale: 0

  chatapp:
    restart: unless-stopped
    image: faust.cs.fau.de:5000/chatapp
    init: true
    build: server
    ports:
      - "3000:5000/tcp"
    environment:
      DB_USER: root
      DB_PASS: example
      DB_NAME: chatapp
      DB_HOST: db
    depends_on:
      - db

networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "fd42:d0ce:4134::/64"
